-- One-time orders had no ceiling. Subscriptions are bounded by the
-- one_active_subscription_per_user index, but place_one_time_order could be
-- called in a loop by any signed-in account — each call minting a real kitchen
-- ticket, a row on the ops board, and revenue in admin_today(). Verified by
-- driving 12 orders through it as an ordinary customer with no resistance.
--
-- Ten a day is far above genuine use (the whole product is a subscription; a
-- one-off is the exception) and far below anything worth scripting. Only
-- one-time orders count: a subscriber's automatic deliveries are generated by
-- cron, not by this function, and must not eat into their manual budget.
create or replace function public.place_one_time_order(
  p_items jsonb,
  p_cutting public.cutting_style default 'cubed'
) returns jsonb
language plpgsql security definer set search_path = public as
$$
declare
  uid uuid := auth.uid();
  total int;
  total_grams int;
  oid uuid;
  d date := public.ist_today() + 1;
  addr uuid;
  recent int;
begin
  if uid is null then raise exception 'sign in first'; end if;

  select count(*) into recent
  from public.orders
  where user_id = uid
    and subscription_id is null
    and created_at > now() - interval '24 hours';
  if recent >= 10 then
    raise exception 'that is a lot of boxes for one day — get in touch and we will sort it out';
  end if;

  select coalesce(sum(line_paise), 0), coalesce(sum(line_grams), 0)
    into total, total_grams from public.priced_items(p_items);
  if total <= 0 then raise exception 'your box is empty'; end if;

  select id into addr from public.addresses where user_id = uid and is_default limit 1;

  insert into public.orders
    (user_id, delivery_date, status, total_paise, grams, cutting, address_id, events)
  values
    (uid, d, 'placed', total, total_grams, p_cutting, addr,
     jsonb_build_array(jsonb_build_object('event', 'placed', 'at', now())))
  returning id into oid;

  insert into public.order_items (order_id, fruit_id, cups, price_paise_per_cup)
  select oid, i.fruit_id, i.cups, f.price_paise
  from public.priced_items(p_items) i join public.fruits f on f.id = i.fruit_id;

  return jsonb_build_object('order_id', oid, 'delivery_date', d, 'total_paise', total);
end
$$;

-- create or replace resets privileges to the default, so re-apply the lockdown.
revoke execute on function public.place_one_time_order(jsonb, public.cutting_style) from public, anon;

-- Index supporting the window count above.
create index if not exists orders_user_created_at on public.orders (user_id, created_at desc)
  where subscription_id is null;
